config/routes.rb
# -*- encoding : utf-8 -*-
Weltel::Application.routes.draw do
	# root
	root(:to => "weltel/dashboards#show", :page => 1, :view => :study)

	mount Authentication::Engine => "/authentication"
	mount Sms::Engine => "/sms"
  mount Feedbacker::Engine => "/feedback"

	# admin
	namespace(:weltel) do
		# tasks
		resource(:task, :only => []) do
			get(:create_records)
			get(:update_records)
			get(:receive_responses)
		end

		# updates
		resource(:update, :only => [:show]) do
			post(:update)
			get(:status)
		end

		# dashboards
		resource(:dashboard, :only => [:show]) do
      get(:log)
    end
    match('/dashboard/study(/page/:page)', :to => 'dashboards#show', :view => 'study', :defaults => {:page => 1}, :as => :study_dashboard)
    match('/dashboard/clinic(/page/:page)', :to => 'dashboards#show', :view => 'clinic', :defaults => {:page => 1}, :as => :clinic_dashboard)

		# patients
		resources(:patients, :only => [:index, :new, :create, :edit, :update, :destroy]) do
			resources(:messages, :controller => :patient_messages, :only => [:index, :new, :create])
			resources(:records, :controller => :patient_records, :only => [:update])
		end

		# responses
		resources(:responses, :only => [:index, :new, :create, :edit, :update, :destroy])

		# clinics
		resources(:clinics, :only => [:index, :new, :create, :edit, :update, :destroy])
	end
end

app/models/weltel/clinic.rb
# -*- encoding : utf-8 -*-
module Weltel
	class Clinic
		include DataMapper::Resource

		# properties
		property(:id, Serial)
		property(:system, Boolean, {:required => true, :default => false})
		property(:name, String, {:unique => true, :allow_nil => false, :allow_blank => true, :length => 64})
		property(:created_at, DateTime)
		property(:updated_at, DateTime)

		# validations
		#validates_length_of(:name, :within => o..64, :allow_blank => true)
		#validates_format_of(:name, :with => /^[\w* ]$/, :allow_blank => true)

		# associations
		has(n, :patients, Weltel::Patient, :constraint => :protect)

		# class methods
		#
		def self.user
			all(:system => false)
		end

		#
		def self.sorted_by(key, order)
			all(:order => [key.send(order)])
		end
	end
end

app/models/weltel/message.rb
# -*- encoding : utf-8 -*-
module Sms
	class Message
		# associations
		belongs_to(:patient_record, Weltel::PatientRecord, :required => false)
	end
end

app/models/weltel/patient_record_state.rb
# -*- encoding : utf-8 -*-
module Weltel
	class PatientRecordState
		include DataMapper::Resource
    VALUES = [:pending, :unknown, :positive, :negative, :late]

		# properties
		property(:id, Serial)
		property(:active, Boolean, {:index => true, :required => true, :default => true})
		property(:value, Enum[*VALUES], {:index => true, :required => true, :default => :unknown})
		property(:created_at, DateTime)

		# associations
		belongs_to(:patient_record, Weltel::PatientRecord)
		belongs_to(:user, Authentication::User, :required => false)

		# class methods
		#
		def self.active
			all(:active => true)
		end
	end
end

app/models/weltel/subscriber.rb
# -*- encoding : utf-8 -*-
module Sms
	class Subscriber
		# associations
		has(1, :patient, Weltel::Patient, :constraint => :destroy)
	end
end

app/controllers/weltel/application_controller.rb
# -*- encoding : utf-8 -*-
require "dm-rails/middleware/identity_map"

module Weltel
	class ApplicationController < ActionController::Base
		use Rails::DataMapper::Middleware::IdentityMap
		protect_from_forgery

	end
end

app/controllers/weltel/clinics_controller.rb
# -*- encoding : utf-8 -*-
module Weltel
	class ClinicsController < ApplicationController
		include Authentication::AuthenticatedController
		respond_to(:html)
		layout("private/application")

    before_filter(:only => :index) do
    	session_param(:clinics, :page, 1)
    	sort_param(:clinics, :name, :asc)
    end

		#
		def index
			@clinics = Weltel::Clinic.user.sorted_by(@sort_key, @sort_order).paginate(:page => 1, :per_page => 2)
			respond_with(@clinics)
		end

		#
		def new
			@clinic = Weltel::Clinic.new
			respond_with(@clinic)
		end

		#
		def create
			begin
				@clinic = Weltel::Clinic.create(params[:weltel_clinic])
				flash[:notice] = t(:created)
				respond_with(@clinic, :location => weltel_clinics_path)

			rescue DataMapper::SaveFailureError => error
				@clinic = error.resource
				respond_with(@clinic) do |format|
					format.html { render(:new) }
				end
			end
		end

		#
		def edit
			@clinic = Weltel::Clinic.get!(params[:id])
			respond_with(@clinic)
		end

		#
		def update
			begin
				@clinic = Weltel::Clinic.get!(params[:id])
				@clinic.update(params[:weltel_clinic])
				flash[:notice] = t(:updated)
				respond_with(@clinic, :location => weltel_clinics_path)

			rescue DataMapper::SaveFailureError => error
				@clinic = error.resource
				respond_with(@clinic) do |format|
					format.html { render(:edit) }
				end
			end
		end


		#
		def destroy
			@clinic = Weltel::Clinic.get!(params[:id])
			@clinic.destroy
			flash[:notice] = t(:destroyed)
			respond_with(@clinic, :location => weltel_clinics_path)
		end

	private
		#
		def t(key)
			I18n.t(key, :scope => [:weltel, :clinics])
		end
	end
end

app/controllers/weltel/connections_controller.rb
module Weltel
  class ConnectionsController < SystemsController
    include Authentication::AuthenticatedController
    respond_to :html

		#
    def edit
      @connection = Adapters::Connection.load_config(:current)
      @available_devices = Adapters::Connection.available_devices
    end

		#
    def update
      params.select! {|k,v| Adapters::Connection.valid_keys.include?(k.to_sym) }
      Adapters::Connection.save_config(:current, params.merge({:type => Weltel::Connection.to_s}))
      @connection = Adapters::Connection.load_config(:current)

      if @connection.type
				connection_class = @connection.type.constantize
				connection_class.reset
			end

      flash[:notice] = t(:updated)

      redirect_to(weltel_system_path)
    end

		#
    def destroy
      @connection = Adapters::Connection.load_config(:current)

      if @connection.type
				connection_class = @connection.type.constantize
				connection_class.reset
      end

      flash[:notice] = t(:destroyed)

      redirect_to(weltel_system_path)
    end

	private
		#
		def t(key)
			I18n.t(key, :scope => [:weltel, :connections])
		end
	end
end

app/controllers/weltel/dashboards_controller.rb
# -*- encoding : utf-8 -*-
module Weltel
	class DashboardsController < ApplicationController
		include Authentication::AuthenticatedController
    include DashboardsHelper

    before_filter do
      page_param(:dashboard)
      sort_param(:dashboard, :user_name, :asc)
      session_param(:view, :per_page, 20)
      session_param(:dashboard, :search, '')
      session_param(:dashboard, :view, :study)
      if is_study_dashboard?(@view)
        session_param(:dashboard, :state, :negative)
      else
        session_param(:dashboard, :status, :open)
      end
    end

		#
		def show
      @patients = Weltel::Patient.active.with_active_record
      if !@search.blank?
        @patients = @patients.search(@search)
      elsif is_study_dashboard?(@view)
        @patients = @patients.with_state(@state.to_sym)
      else
        @patients = @patients.with_status(@status.to_sym)
      end

      @patients = @patients.sorted_by(@sort_key, @sort_order)

      @print = params[:print]
      @patients = @patients.paginate(:page => @page, :per_page => @per_page) if @print.blank?

      respond_to do |format|
        if @print.blank?
          format.html { render :layout => 'private/application' }
        else
          format.html { render 'print', :layout => 'private/print' }
        end
      end
		end

	private
		#
		def t(key)
			I18n.t(key, :scope => [:weltel, :dashboards])
		end
	end
end

app/controllers/weltel/demos_controller.rb
module Weltel
  class DemosController < SystemsController
    respond_to :html

    def show
    end
  end
end

app/controllers/weltel/logs_controller.rb
module Weltel
  class LogsController < SystemsController
    def show
      @filename = params[:id]
      @log = File.open(File.join(Rails.root, 'log', @filename), 'r').read
    end

    def destroy
      @filename = params[:id]
      File.open(File.join(Rails.root, 'log', @filename), 'w') {|f| f.write('')}
      flash[:notice] = t(".destroyed")
      redirect_to(weltel_system_path)
    end

	private
		#
		def t(key)
			I18n.t(key, :scope => [:weltel, :logs])
		end
	end
end

app/controllers/weltel/patient_checkups_controller.rb
#-  -*- encoding : utf-8 -*-
#- This Source Code Form is subject to the terms of the Mozilla Public
#- License, v. 2.0. If a copy of the MPL was not distributed with this
#- file, You can obtain one at http://mozilla.org/MPL/2.0/.

module Weltel
	class PatientCheckupsController < ApplicationController
		include Authentication::AuthenticatedController
		respond_to(:html)
		layout("private/application")

    #
		def update
			weltel_checkup = params[:weltel_checkup]
      @patient = Weltel::Patient.find(params[:patient_id])
      @checkup = @patient.checkups.find(params[:id])

      current_result = weltel_checkup[:current_result]
      if current_result
				@checkup.change_result(current_result.to_sym, authenticated_user)
				@checkup.reload
			end

			weltel_checkup = weltel_checkup.select{|k,v| [:status].include?(k.to_sym)}
      @checkup.assign_attributes(weltel_checkup)
      @checkup.save!

      redirect_to(weltel_dashboard_path)
		end
  end
end

app/controllers/weltel/patient_messages_controller.rb
# -*- encoding : utf-8 -*-
module Weltel
	class PatientMessagesController < ApplicationController
		include Authentication::AuthenticatedController
		respond_to(:html)
		layout("private/application")

    before_filter(:only => :index) do
    	page_param(:patient_messages)
      sort_param(:patient_messages, :updated_at, :desc)
    end

		# list messages for patient
		def index
			@patient = Weltel::Patient.get!(params[:patient_id])
			@messages = @patient.subscriber.messages.sorted_by(@sort_key, @sort_order).paginate(:page => @page, :per_page => 20)

			@messages.select {|message| message.status == :received}.each do |message|
				message.update(:status => :read)
			end

			respond_with(@patient, @messages)
		end

		# new message form for patient
		def new
			@patient = Weltel::Patient.get!(params[:patient_id])
			@message = @patient.subscriber.messages.new
			@message_templates = Sms::MessageTemplate.user

			respond_with(@patient, @message)
		end

		# create a new message for patient
		def create
			begin
				@patient = Weltel::Patient.get!(params[:patient_id])

				body = params[:message][:body]
				if body.empty?
					body = Sms::MessageTemplate.get!(params[:message_template_id]).body
				end

				Weltel::Patient.transaction do
					if @patient.active_record
						@message = @patient.active_record.create_outgoing_message(body)
					else
						@message = @patient.subscriber.create_outgoing_message(body)
					end

					Weltel::Factory.sender.send(@message)
				end

				flash[:notice] = t(:created)

				respond_with(@message, :location => weltel_patient_messages_path(@patient))

			rescue DataMapper::SaveFailureError => error
				@message = error.resource
				@message_templates = Sms::MessageTemplate.user
				respond_with(@message) do |format|
					format.html { render(:new) }
				end
			end
		end
	private
		#
		def t(key)
			I18n.t(key, :scope => [:weltel, :patient_messages])
		end
	end
end

app/controllers/weltel/patient_records_controller.rb
# -*- encoding : utf-8 -*-
module Weltel
	class PatientRecordsController < ApplicationController
		include Authentication::AuthenticatedController
		respond_to(:html)
		layout("private/application")

    #
		def update
      @patient = Weltel::Patient.get!(params[:patient_id])
      @patient_record = @patient.records.get(params[:id])

      @patient_record.change_state(params[:current_state].to_sym, authenticated_user) if params[:current_state]
      @patient_record.reload
      @patient_record.update(params.select{|k, v| [:status, :contact_method].include?(k.to_sym)})

      redirect_to(weltel_dashboard_path)
		end
  end
end

app/controllers/weltel/patients_controller.rb
#-  -*- encoding : utf-8 -*-
#- This Source Code Form is subject to the terms of the Mozilla Public
#- License, v. 2.0. If a copy of the MPL was not distributed with this
#- file, You can obtain one at http://mozilla.org/MPL/2.0/.

# -*- encoding : utf-8 -*-
module Weltel
	class PatientsController < ApplicationController
		include Authentication::AuthenticatedController
		respond_to(:html)
		layout("private/application")

		#
    before_filter(:only => :index) do
    	session_param(:patients, :search, "")
    	page_param(:patients, 20)
      sort_param(:patients, :user_name, :asc)
      filter_param(:patients)
    end

		# patient list
		def index
			@clinics = Weltel::Clinic
				.sorted_by("name", :asc)

			@patients = Weltel::Patient
				.joins{subscriber}
				.joins{clinic.outer}
				.search(@search)
				.filtered_by(@filter_attribute, @filter_value)
				.sorted_by(@sort_attribute, @sort_order)
				.paginate(:page => @page, :per_page => @per_page)

			respond_to do |format|
				format.html { @patients }
      	format.csv { send_data Weltel::Patient.to_csv }
			end
			# respond_with(@patients)
		end

		# new patient form
		def new
			@patient = Weltel::Patient.new
			@patient.subscriber = Sms::Subscriber.new
			respond_with(@patient)
		end

		# create new patient
		def create
			begin
				Weltel::Patient.transaction do
					weltel_patient = params[:weltel_patient]
					@patient = Weltel::Patient.create!(weltel_patient)
					flash[:notice] = t(:created)
					respond_with(@patient, :location => weltel_patients_path)
				end

			rescue ActiveRecord::RecordInvalid => error
				@patient = error.record
				respond_with(@patient) do |format|
					format.html { render(:new) }
				end
			end
		end

		# edit patient form
		def edit
			@patient = Weltel::Patient.find(params[:id])
			respond_with(@patient)
		end

		# update patient
		def update
			begin
				Weltel::Patient.transaction do
					weltel_patient = params[:weltel_patient]
					@patient = Weltel::Patient.find(params[:id])
					@patient.assign_attributes(weltel_patient)
					@patient.save!
					flash[:notice] = t(:updated)
					respond_with(@patient, :location => weltel_patients_path)
				end

			rescue ActiveRecord::RecordInvalid => error
				@patient = error.record
				respond_with(@patient) do |format|
					format.html { render(:edit) }
				end
			end
		end

		#
		def destroy
			Weltel::Patient.transaction do
				@patient = Weltel::Patient.find(params[:id])
				@patient.destroy
				flash[:notice] = t(:destroyed)
				respond_with(@patient, :location => weltel_patients_path)
			end
		end

	private
		#
		def t(key)
			I18n.t(key, :scope => [:weltel, :patients])
		end
	end
end

app/controllers/weltel/responses_controller.rb
#-  -*- encoding : utf-8 -*-
#- This Source Code Form is subject to the terms of the Mozilla Public
#- License, v. 2.0. If a copy of the MPL was not distributed with this
#- file, You can obtain one at http://mozilla.org/MPL/2.0/.

# -*- encoding : utf-8 -*-
module Weltel
	class ResponsesController < ApplicationController
		include Authentication::AuthenticatedController
		respond_to(:html)
		layout("private/application")

		#
    before_filter(:only => :index) do
    	page_param(:responses, 20)
      sort_param(:responses, :name, :asc)
      filter_param(:responses)
    end

		#
		def index
			@responses = Weltel::Response
				.filtered_by(@filter_attribute, @filter_value)
				.sorted_by(@sort_attribute, @sort_order)
				.paginate(:page => @page, :per_page => @per_page)

			respond_to do |format|
				format.html { @responses }
      	format.csv { send_data Weltel::Response.to_csv }
			end
			# respond_with(@responses)
		end

		#
		def new
			@response = Weltel::Response.new
			respond_with(@response)
		end

		#
		def create
			begin
				weltel_response = params[:weltel_response]
        if weltel_response[:url_encoded]
          weltel_response[:name] = CGI::unescape(weltel_response[:name])
          weltel_response.delete(:url_encoded)
        end
				@response = Weltel::Response.create!(weltel_response)
				flash[:notice] = t(:created)
				respond_with(@response, :location => weltel_responses_path)

			rescue ActiveRecord::RecordInvalid => error
				@response = error.record
				respond_with(@response) do |format|
					format.html { render(:new) }
				end
			end
		end

		#
		def edit
			@response = Weltel::Response.find(params[:id])
			respond_with(@response)
		end

		#
		def update
			begin
				weltel_response = params[:weltel_response]
				@response = Weltel::Response.find(params[:id])
				@response.assign_attributes(weltel_response)
				@response.save!
				flash[:notice] = t(:updated)
				respond_with(@response, :location => weltel_responses_path)

			rescue ActiveRecord::RecordInvalid => error
				@response = error.record
				respond_with(@response) do |format|
					format.html { render(:edit) }
				end
			end
		end

		#
		def destroy
			@response = Weltel::Response.find(params[:id])
			@response.destroy
			flash[:notice] = t(:destroyed)
			respond_with(@response, :location => weltel_responses_path)
		end

	private
		#
		def t(key)
			I18n.t(key, :scope => [:weltel, :responses])
		end
	end
end

app/views/weltel/dashboards/_checkup_contact_method_select.html.haml
= form_for(checkup, :url => weltel_patient_checkup_path(patient, checkup)) do |f|
  = select_tag(:contact_method, options_for_select(checkup_contact_method_options, checkup.contact_method), :onchange => submit_form)

app/views/weltel/dashboards/_checkup_status_select.html.haml
= form_for(checkup, :url => weltel_patient_checkup_path(patient, checkup)) do |f|
  = f.select(:status, |
    options_for_select(checkup_status_options, checkup.status), |
    {}, |
    :onchange => submit_form, :class => "status #{checkup.status}")

app/views/weltel/dashboards/_clinical_table.html.haml
//- This Source Code Form is subject to the terms of the Mozilla Public
//- License, v. 2.0. If a copy of the MPL was not distributed with this
//- file, You can obtain one at http://mozilla.org/MPL/2.0/.

%table
  %tr
    = sorted_table_header_tag(:user_name) do
      = t(".user_name")

    = sorted_table_header_tag(:study_number) do
      = t(".study_number")

    //= sorted_table_header_tag("initial_result.value") do
    //= t(".initial_result")

    = sorted_table_header_tag("current_result.value") do
      = t(".current_result")

    = table_header_tag(t(".status"))

    //= filter_table_header_tag("current_checkup.contact_method", checkup_contact_method_options) do
    //= t(".contact_method")

    = filter_table_header_tag("clinic.name", clinic_name_options) do
      = t(".clinic")

    %th.actions
      .title= t(".actions")
      .print
        = link_to t(".print"), params.merge(:print => true), :target => "_blank"

  - if @patients.empty?
    %tr
      %td{:colspan => 8}
        .empty_search= t(".no_patients")
  - else
    = render({:collection => @patients, :partial => "row", :as => :patient})

app/views/weltel/dashboards/_clinical_tabs.html.haml
- Weltel::Checkup::STATUSES.each do |status|
  .tab{:class => active_class(status == @status && @search.blank?)}
    .content
      = link_to(checkup_status_t(status), params.merge(:status => status, :page => 1), :class => "#{active_class(status == @status)} #{status} status")

app/views/weltel/dashboards/_result_value_select.html.haml
- value = result_value(result)
= form_for(checkup, :url => weltel_patient_checkup_path(patient, checkup)) do |f|
  = f.select(:current_result, |
    options_for_select(result_value_options, value), |
    {}, |
    :onchange => submit_form, :class => "current_state #{value}")

- content_for(:scripts) do
  :javascript
    $(function() {
      $('select.current_result').live('change', function(e) {
        var klass = $(e.target).find(':selected').attr('class');
        $(e.target).attr('class', 'current_state state ' + klass);
      });
    });

app/views/weltel/dashboards/_row.html.haml
%tr.patient_first.item
  %td
    %h3= link_to(patient.user_name, edit_weltel_patient_path(patient))
  %td
    %h3= patient.study_number
  %td
    = initial_state_tag(patient)
  %td
    = form_for(patient.active_record, :url => weltel_patient_record_path(patient, patient.active_record)) do |f|
      = select_tag(:current_state, options_for_select(patient_record_state_options, patient.active_record.active_state.value), :onchange => submit_form, :class => "current_state #{patient.active_record.active_state.value}")
  %td
    = form_for(patient.active_record, :url => weltel_patient_record_path(patient, patient.active_record)) do |f|
      = select_tag(:status, options_for_select(patient_record_status_options, patient.active_record.status), :onchange => submit_form, :class => "status #{patient.active_record.status}")
  %td
    = form_for(patient.active_record, :url => weltel_patient_record_path(patient, patient.active_record)) do |f|
      = select_tag(:contact_method, options_for_select(patient_record_contact_method_options, patient.active_record.contact_method), :onchange => submit_form)
  %td
    = patient.clinic.name
  %td.actions
    = link_to(t(".messages_link", :count => patient.subscriber.messages.received.count), weltel_patient_messages_path(patient), :class => "button")
    = link_to('+', '#', :class => 'toggle_details')

%tr.patient_last
  - first_sent = patient.active_record.messages.sent.first
  %td.first{:colspan => 4}
    - if first_sent
      - first_received = patient.active_record.messages.received_or_read.first
      - if first_sent
        %h3 Initial response
        = exchange_tag(nil, first_received, [nil, 'messaging.no_initial_receive'])
    - else
      = exchange_tag(nil, nil, ['messaging.no_initial_send', nil])
  %td.last{:colspan => 5}
    - if first_received
      %h3 Most recent messages
      = exchange_tag(patient.active_record.messages.sent.last, patient.active_record.messages.received_or_read.last)


app/views/weltel/dashboards/_study_table.html.haml
//- This Source Code Form is subject to the terms of the Mozilla Public
//- License, v. 2.0. If a copy of the MPL was not distributed with this
//- file, You can obtain one at http://mozilla.org/MPL/2.0/.

%table
  %tr
    = sorted_table_header_tag(:user_name) do
      = t(".user_name")

    = sorted_table_header_tag(:study_number) do
      = t(".study_number")

    //= sorted_table_header_tag("initial_result.value") do
    //= t(".initial_result")

    = table_header_tag(t(".current_result"))

    = sorted_table_header_tag("current_checkup.status") do
      = t(".status")

    //= filter_table_header_tag("current_checkup.contact_method", checkup_contact_method_options) do
    //= t(".contact_method")

    = filter_table_header_tag("clinic.name", clinic_name_options) do
      = t(".clinic")

    %th.actions
      .title= t(".actions")
      .print
        = link_to t(".print"), params.merge(:print => true), :target => "_blank"

  - if @patients.empty?
    %tr
      %td{:colspan => 8}
        .empty_search= t(".no_patients")
  - else
    = render({:collection => @patients, :partial => "row", :as => :patient})

app/views/weltel/dashboards/_study_tabs.html.haml
- ResultsHelper::RESULT_VALUES.each do |value|
  .tab{:class => active_class(value == @state && @search.blank?)}
    .content
      = link_to(result_value_t(value), params.merge(:state => value, :page => 1), :class => "#{active_class(value == @state)} #{value} state")

app/views/weltel/dashboards/_table.html.haml
%table
  %tr
    = sorted_table_header_tag(:user_name) do
      = t(".user_name")
    = sorted_table_header_tag(:study_number) do
      = t(".study_number")
    = table_header_tag(t(".initial_state"))
    = table_header_tag(t(".current_state"))
    = table_header_tag(t(".status"))
    = table_header_tag(t(".contact_method"))
    = table_header_tag(t(".clinic"))
    %th.actions
      .title= t(".actions")
      .print
        = link_to t('.print'), params.merge(:print => true), :target => '_blank'

  = render({:collection => @patients, :partial => "row", :as => :patient})

app/views/weltel/dashboards/print.html.haml
%table
  %tr
    = table_header_tag(t(".user_name"))
    = table_header_tag(t(".study_number"))
    = table_header_tag(t(".initial_state"))
    = table_header_tag(t(".current_state"))
    = table_header_tag(t(".status"))
    = table_header_tag(t(".contact_method"))
    = table_header_tag(t(".clinic"))
    = table_header_tag(t(".notes"))

  - @patients.each do |p|
    %tr
      %td= p.user_name
      %td= p.study_number
      %td= t("weltel.patient_record_states.values.#{p.active_record.initial_state.value}")
      %td= p.active_record.state_changed? ? t("weltel.patient_record_states.values.#{p.active_record.active_state.value}") : ''
      %td= p.active_record.status.to_s
      %td= p.active_record.contact_method_s
      %td= p.clinic.name
      %td 

app/views/weltel/dashboards/show.html.haml
- content_for(:tabs) do
  = form_tag(weltel_dashboard_path, :method => :get) do
    = hidden_field_tag(:page, 1)
    = search_field_tag(:search, @search, {:size => 40, :tabindex => 1, :onsearch => submit_form})
    = submit_tag(t(".search"))

  - if is_study_dashboard?(@view)
    - Weltel::PatientRecordState::VALUES.each do |state|
      .tab{:class => active_class(state == @state && @search.blank?)}
        .content
          = link_to(t("weltel.patient_record_states.values.#{state}"), params.merge(:state => state, :page => 1), :class => "#{active_class(state == @state.to_sym)} #{state.to_s} state")
  - else
    - Weltel::PatientRecord::STATUSES.each do |status|
      .tab{:class => active_class(status == @status && @search.blank?)}
        .content
          = link_to(t("weltel.patient_records.statuses.#{status}"), params.merge(:status => status, :page => 1), :class => "#{active_class(status == @status.to_sym)} #{status.to_s} status")

- if @patients.empty?
  .empty_search
    = t(".no_patients")
- else
  = render("table")

  - content_for(:footer) do
    = will_paginate(@patients)

- content_for(:scripts) do
  :javascript
    $(function() {
      $('a.toggle_details').live('click', function(e) {
        $(e.target).parents('tr').next().toggle();
        return false;
      });

      $('select.current_state').live('change', function(e) {
        var klass = $(e.target).find(':selected').attr('class');
        $(e.target).attr('class', 'current_state state ' + klass);
      });
      $('td.actions .toggle_details').live('click', function(e) {
        $(e.target).parents('tr').toggleClass('open');
      });
    });